# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
use_frameworks!

target 'LeanStorageDemoSwift' do
    pod 'AVOSCloudDynamic', '3.1.5.2'
end

target 'LeanStorageDemoSwiftTests' do
    
end

