# Uncomment this line to define a global platform for your project
platform :ios, '7.0'
use_frameworks!

target 'LeanStorageDemo' do
    pod 'AVOSCloud' , '3.1.3.4'
    pod 'LZAlertViewHelper', '0.0.2'
end
